### ISSUE TITLE
Bug: floating task goes into scheduled task

### ISSUE THREAD

**Issue by ypbisma** [cs2103jan2015-t10-1c/main#63]

**Comment by christianhw** [comment]
I know why this happens.
When I change the code for location such that it can accept more than one word, I made a mistake, such that the tags are not initialised into newEntry. As a result, this probably affects the parsing for date and time as well.
Bisma and I have resolved this bug in our respective codes, but we haven't pushed. Hence, Nguyen's code doesn't work during demo. I have run my code again, and it works perfectly well.
